### ISSUE TITLE
message_cycle() does not work

### ISSUE THREAD

**Issue by Xohn** [jaydeepakbari/Chat-Like-Facebook-Using-PHP-MYSQL#1]
I downloaded your code and try to make it work in my computer
but I found that the instant message doesn't work 
I need to refresh the page to get the new message
I need your help

**Comment by jaydeepakbari** [comment]
please try again b'coz this code is working fine in my computer or machine

**Comment by guruhyes** [comment]
![capture](https://cloud.githubusercontent.com/assets/17075371/21601185/c11fe8cc-d1b9-11e6-937f-fccc26212c35.PNG)

where div#2 refer to?
because message cycle not working

**Comment by jaydeepakbari** [comment]
Replace that line "$("#jd-chat").find("div#2").parents(".jd-user");"

with

$("#jd-chat").find("div#" + user ).parents(".jd-user");
